UI modification for sponsor buttons
responsively-org/website pull request #48
Opened 2024-04-21 23:02 UTC by maximdudai

Before:
<img width="359" alt="image" src="https://github.com/responsively-org/website/assets/108686152/26e82850-e6bf-4e96-a851-f4c5d848afa9">

After:
<img width="597" alt="image" src="https://github.com/responsively-org/website/assets/108686152/7287a8be-40c2-44d0-84ec-00150b62561e">

2024-04-21 23:02 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/responsively-org/website?pullRequest=48) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/responsively-org/website?pullRequest=48) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/responsively-org/website?pullRequest=48) it.</sub>

2024-04-22 03:52 UTC, manojVivek requested changes
Just a minor change request, looks great otherwise!

2024-04-22 03:52 UTC, manojVivek commented on src/images/logos/github-white.png
The cut on the top and bottom feels strange, can you please swap it with the one that has the full circle?

2024-04-23 11:55 UTC, maximdudai commented on src/images/logos/github-white.png
I don't know why I didn't realize right away that it didn't look decent 🤣, but it's fixed now 👍

2024-04-23 12:14 UTC, maximdudai commented
I made a small mistake 🫠 the branch was accidentally deleted by me before it was merged. I've just reopened the pull request to enable merging. I apologize for any inconvenience this may have caused. :)

2024-04-24 09:40 UTC, manojVivek approved these changes
Looks great! Thank you for your contribution!

2024-04-24 09:41 UTC, merged